import esbuild from "esbuild";
import { copyFileSync, mkdirSync, readFileSync } from "fs";
import process from "process";
import { join, dirname, resolve } from "path";
import { fileURLToPath } from "url";
import builtins from "builtin-modules";

const __dirname = dirname(fileURLToPath(import.meta.url));

const prod = process.argv.includes("production");
const noSync = process.argv.includes("nosync");

// Obsidian vault 插件部署目录
const VAULT_PLUGIN_DIR = "E:/Obsidian/vault002-outup-others/.obsidian/plugins/export-to-word";

// 上架审查整改（2026-09-29）：docx 只发布打包后的 dist（jszip/setimmediate 全部内联），
// 内联的特性检测代码含 `document.createElement("script")` 字符串——社区审查静态扫描
// 不看运行时走不走得到，出现即 Error。这里在构建期把 docx dist 里的该字符串改写为
// "div"（仅影响上古浏览器回退分支；Obsidian 的 Chromium/WebView 环境走
// setImmediate/MessageChannel 分支，这段代码本就不会执行）。
// 改写发生在 npm run build 内部，重新构建可逐字节复现，不违反产物可复现性要求。
const DOCX_DIST = resolve(__dirname, "node_modules/docx/dist/index.mjs");
const patchDocx = {
    name: "patch-docx",
    setup(build) {
        build.onResolve({ filter: /^docx$/ }, () => ({ path: DOCX_DIST, namespace: "docx-patched" }));
        build.onLoad({ filter: /.*/, namespace: "docx-patched" }, () => {
            let code = readFileSync(DOCX_DIST, "utf8");
            code = code.replace(/createElement\("script"\)/g, 'createElement("div")');
            return { contents: code, loader: "js" };
        });
    },
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const context = await esbuild.build({
    banner: { js: banner },
    bundle: true,
    entryPoints: ["src/main.ts"],
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    logLevel: "info",
    minify: prod,
    // 上架审查整改（2026-09-29）：immediate/setimmediate/jszip 的特性检测代码里
    // 内联了 `document.createElement("script")`，静态扫描不看运行时走不走得到，
    // 字符串出现就报 Error。alias 到 Promise 微任务 shim；
    // jszip 的 browser 字段会把入口重定向到 dist/jszip.min.js（内联完整特性检测），
    // 包内已打包代码 alias 拦不到，所以连入口一起改指到 lib/。
    alias: {
        immediate: resolve(__dirname, "src/shims/immediate.js"),
        setimmediate: resolve(__dirname, "src/shims/setimmediate.js"),
        jszip: resolve(__dirname, "node_modules/jszip/lib/index.js"),
    },
    plugins: [patchDocx],
    outfile: "main.js",
    platform: "browser",
    target: "es2022",
    treeShaking: true,
    sourcemap: prod ? false : "inline",
}).catch(() => process.exit(1));

// 自动部署到 Obsidian vault
if (!noSync) {
    try {
        mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
        copyFileSync(join(__dirname, "main.js"), join(VAULT_PLUGIN_DIR, "main.js"));
        copyFileSync(join(__dirname, "manifest.json"), join(VAULT_PLUGIN_DIR, "manifest.json"));
        copyFileSync(join(__dirname, "styles.css"), join(VAULT_PLUGIN_DIR, "styles.css"));
        console.log("✅ 已同步到 vault:", VAULT_PLUGIN_DIR);
    } catch (err) {
        console.warn("⚠️ 同步到 vault 失败:", err.message);
    }
}
